farmproject/farmapp/urls.py
from .import views
from django.urls import path
app_name='farmapp'
urlpatterns = [
    path('',views.fun,name='fun'),
    path('farm/<int:farm_id>/',views.detail,name='detail'),
    path('add/',views.add_farm,name='add_farm'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    ]

farmproject/farmproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("farmapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                                      document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

farmproject/farmapp/models.py
from pyclbr import Class

from django.db import models

# Create your models here.

class Farm(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='gallary')
    def __str__(self):
        return self.name

farmproject/farmapp/forms.py
from django import forms
from . models import Farm
class FarmForm(forms.ModelForm):
    class Meta:
        model=Farm
        fields=['name','desc','price','img']

farmproject/farmapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from farmapp.models import Farm
from . forms import FarmForm

def fun(request):
    farm=Farm.objects.all()
    context={
        'farm_list':farm
    }
    return render(request,'index.html',context)
def detail(request,farm_id):
    farm=Farm.objects.get(id=farm_id)
    return render(request,"detail.html",{'farm':farm})
def add_farm(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        price= request.POST.get('price',)
        img = request.FILES['img']
        farm=Farm(name=name,desc=desc,price=price,img=img)
        farm.save()
        return redirect('/')
    return render(request,'add.html')
def update(request,id):
    farm=Farm.objects.get(id=id)
    form=FarmForm(request.POST or None,request.FILES,instance=farm)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'farm':farm})
def delete(request,id):
    if request.method == "POST":
        farm = Farm.objects.get(id=id)
        farm.delete()
        return redirect('/')
    return render(request, 'delete.html')

farmproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your fruit name">
    <input type="text" name="desc" placeholder="description">
    <input type="text" name="price" placeholder="enter your plants price">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

farmproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">
      Farm store
    </a>
  </div>
    <div>
       <a href="{% url 'farmapp:add_farm' %}" class="btn btn-primary">add</a>
    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

farmproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    are you sure to delete this fruit plant
    <input type="submit">
</form>

farmproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
         <img src="{{farm.img.url}}" style="width:250px; height:250px;">
        </div>
        <div class="col-md-6">
         <h2>{{farm.name}}</h2>
         <h6> {{farm.desc}}</h6>
         <h6>{{farm.price}}  </h6>
            <a class="btn btn-warning" href="{% url 'farmapp:update' farm.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'farmapp:delete' farm.id %}">delete</a><br>
        </div>
    </div>
</div>
{% endblock %}

farmproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

farmproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
            {% for i in farm_list %}
            <div class="col-sm-4 py-2">
                <div class="card deck h-100" style="min-width: 18rem;">
                    <img src="{{i.img.url}}" class="card-img-top" alt="card_image" style="width:100%;height:200px;">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.desc}}</p>
                        <a href="{% url 'farmapp:detail' i.id %}" class="btn btn-primary">for more</a>
                    </div>

                </div>
            </div>
            {% endfor %}

    </div>
</div>

{% endblock %}